name: HappyWatch
options:
  bundleIdPrefix: com.slopus.happy
  deploymentTarget:
    watchOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    GENERATE_INFOPLIST_FILE: "YES"

packages:
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    from: "24.0.0"

targets:
  HappyWatchApp:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: HappyWatchApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.slopus.happy.dev.watchapp
        INFOPLIST_KEY_CFBundleDisplayName: "Happy"
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: "com.slopus.happy.dev"
        INFOPLIST_KEY_WKWatchOnly: "NO"
        CODE_SIGN_ENTITLEMENTS: HappyWatchApp/HappyWatchApp.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
        PRODUCT_NAME: Happy
        PRODUCT_MODULE_NAME: HappyWatchApp
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_STRICT_CONCURRENCY: minimal
    dependencies:
      - package: KeychainSwift

  HappyWatchWidgets:
    type: app-extension
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: HappyWatchWidgets
      - path: HappyWatchApp/Models
        group: Shared/Models
      - path: HappyWatchApp/Utilities/AppGroupStorage.swift
        group: Shared/Utilities
      - path: HappyWatchApp/DesignSystem/HappyColors.swift
        group: Shared/DesignSystem
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.slopus.happy.dev.watchapp.widgets
        INFOPLIST_KEY_CFBundleDisplayName: "Happy Widgets"
        CODE_SIGN_ENTITLEMENTS: HappyWatchWidgets/HappyWatchWidgets.entitlements
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_STRICT_CONCURRENCY: minimal

  HappyWatchTests:
    type: bundle.unit-test
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: HappyWatchTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.slopus.happy.dev.watchapp.tests
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
        SWIFT_STRICT_CONCURRENCY: minimal
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Happy.app/Happy"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_TARGET_NAME: HappyWatchApp
    dependencies:
      - target: HappyWatchApp
